# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

gems:
  - jekyll-redirect-from
  - jekyll-sitemap

# Social
title: Converthtml
description: Converthtml help you convert your original html into a colorful one, which is useful for html-style tutorial/demo pages. Converthtml is designed with many colorful themes for you to choose.
twitter: https://twitter.com/mtu_truong
authors: Tuds - Crazychicken
social_logo_path: https://converthtml.amptype.com/theme/images/about-convert.png
social_image_path: https://converthtml.amptype.com/theme/images/about-convert.png

# Custom vars
current_version:  1.0.2
repo:             https://github.com/crazychicken/converthtml.git

download:
  source:         https://github.com/crazychicken/converthtml/archive/master.zip
  dist:           https://github.com/crazychicken/converthtml/archive/master.zip

blog:             https://converthtml.amptype.com/documents.html
expo:             https://converthtml.amptype.com
themes:           https://converthtml.amptype.com
